package strings.bitmanipulation;
/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"


Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
 */
public class FinfThDifferenceBetweenStrings {
    public static void main(String[] args){
        String s = "abcd";
        String t = "abcde";
        System.out.println(findTheDifference(s, t)); // Output: "e"
    }

    private static  char findTheDifference(String s, String t) {
        char result = 0;

        // XOR all characters in both strings
        for (char c : s.toCharArray()) {
            result ^= c;
        }
        for (char c : t.toCharArray()) {
            result ^= c;
        }

        return result;
    }
}


